In [12]:
import numpy as np
import matplotlib.pyplot as plt
#import json
#from scipy import stats
#import scipy.interpolate as interp
from pprint import pprint
%matplotlib inline
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 14

In [13]:
from sez import *

## Definizione Dati

Griglia di modellazione

In [14]:
a = 1.    # dimensione lato 1
b = 1.    # dimensione lato 2

shape = 'cir'   # tipo forma ['rect', 'ell', 'cir']

gr = 3 # num nodi lato 2 o 3
ne = 16 # num elementi per larghezza e altezza

E = 1. # modulo di Young
ν = 0.33 # coeff. Poisson

off_x = 0. # offset in x
off_y = 0. # offset in y

Setup della sezione

In [15]:
sez1 = Section(a,b,shape)
sez1.setup(ne, ne, gr, E, ν, off_x, off_y)

Generazione dei dati

In [16]:
sez1.generazione_dati()

In [17]:
sez1.F

array([[ 1.  ,  0.33,  0.33,  0.  ,  0.  ,  0.33],
       [ 0.33,  1.  ,  0.  ,  0.  ,  0.  ,  0.33],
       [ 0.  ,  0.  ,  2.66,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  2.66,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  2.66,  0.  ],
       [ 0.33,  0.33,  0.  ,  0.  ,  0.  ,  1.  ]])

In [18]:
sez1.D

array([[ 0.37593985,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.14835461,  1.19582809, -0.29670922,  0.        ,  0.        ,
        -0.29670922],
       [ 0.03680979, -0.29670922,  1.19582809,  0.        ,  0.        ,
        -0.29670922],
       [ 0.        ,  0.        ,  0.        ,  0.37593985,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.37593985,
         0.        ],
       [ 0.03680979, -0.29670922, -0.29670922,  0.        ,  0.        ,
         1.19582809]])

In [19]:
t = [2, 0, 1, 3, 4, 5]
sez1.D[:, t][t]

array([[ 1.19582809,  0.03680979, -0.29670922,  0.        ,  0.        ,
        -0.29670922],
       [ 0.        ,  0.37593985,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.29670922, -0.14835461,  1.19582809,  0.        ,  0.        ,
        -0.29670922],
       [ 0.        ,  0.        ,  0.        ,  0.37593985,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.37593985,
         0.        ],
       [-0.29670922,  0.03680979, -0.29670922,  0.        ,  0.        ,
         1.19582809]])

In [20]:
sez1.D[t][t]

array([[-0.14835461,  1.19582809, -0.29670922,  0.        ,  0.        ,
        -0.29670922],
       [ 0.03680979, -0.29670922,  1.19582809,  0.        ,  0.        ,
        -0.29670922],
       [ 0.37593985,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.37593985,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.37593985,
         0.        ],
       [ 0.03680979, -0.29670922, -0.29670922,  0.        ,  0.        ,
         1.19582809]])

In [21]:
sez1.H

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  1.]])

In [24]:
sez1.tabe[-4:,-4:]

array([[ 1050.,  1081.,  1082.,  1083.],
       [ 1052.,  1083.,  1084.,  1085.],
       [ 1054.,  1085.,  1086.,  1087.],
       [ 1056.,  1087.,  1088.,  1089.]])